### PR TITLE
HKG: add Kia Seltos 2023-24 Non-SCC platform

### PR DESCRIPTION
**Pull request by sunnyhaibin**
**Checklist**
- [x] harness Type: [Hyundai L](https://github.com/commaai/openpilot/wiki/Hyundai-Kia-Genesis#harness-guide)
- [x] architecture: CAN

**Link to all physical parts during installation**
  - [comma 3X](https://comma.ai/shop/comma-3x)
  - [car harness kit](https://comma.ai/shop/car-harness)
    - [Hyundai L](https://github.com/commaai/openpilot/wiki/Hyundai-Kia-Genesis#harness-guide)

Thanks to the community 2024 Kia Seltos Non-SCC owner jeroid_ (Discord).

### CODE REVIEW

**Comment by Stupefacient** [comment]
Did you mean to pr this sunypilot or openpilot bro?

**Comment by sunnyhaibin** [comment]
> Did you mean to pr this sunypilot or openpilot bro?

It is meant for sunnypilot as it does not have SCC :)

**Comment by Moodkiller** [comment]
@sunnyhaibin - hello hello 👋🏼, any objection if we expand this PR to support a 2023 Kia Seltos non-scc as well? 

Harness is the same as above: Hyundai L 
Hardware is a C3

Issues / bug so far:

- Forward collision avoidance gets switched off / disabled (just confirming). Lamp indication is `ON` on instrument cluster as well.
- Assuming this will be fixed with the added finger printing, but upon first install and connection to the car, it does take a few restarts of C3 and car to successfully detect. If I recall, the error was the classic "CAN connection failure, check cables"
- Steering control seems to drop off at random when stopped and only becomes active again after a +-25km/h OR changing lanes / inputting manual steering. I haven't been able to pinpoint the exact cause but can definitely say it stops getting applied. Will see if I can locate a route with this.
- Once in a blue moon, the car will freak out and display the "take break" on the instrument cluster, while C3 errors and has the "take control immediately". No route saved, will make note of this next time.
- In order to activate MADS, I have to press the LKAS button first, and then Cruise Main.
- "Camera Frame Rate Low" alert is shown every time when car starts.
- Shifting gear into S / manual mode causes C3 to freak out.

Let me know if you need any more info <3

Full FW dump:
```               
'carFw': [{'address': 2004,
                          'brand': 'hyundai',
                          'bus': 1,
                          'ecu': 'eps',
                          'fwVersion': b'\xf1\x00SP2 MDPS C 1.00 1.01 56300Q5920          ',
                          'logging': False,
                          'obdMultiplexing': True,
                          'request': [b'"\xf1\x00'],
                          'responseAddress': 2012,
                          'subAddress': 0},
                         {'address': 2017,
                          'brand': 'hyundai',
                          'bus': 1,
                          'ecu': 'transmission',
                          'fwVersion': b'\xf1\x006V2B0_C2\x00\x006V2D4051\x00\x00CSP2N20KL1\xf1\xf7\xe2\x10',
                          'logging': False,
                          'obdMultiplexing': True,
                          'request': [b'"\xf1\x00'],
                          'responseAddress': 2025,
                          'subAddress': 0},
                         {'address': 2001,
                          'brand': 'hyundai',
                          'bus': 1,
                          'ecu': 'abs',
                          'fwVersion': b'\xf1\x00SP ESC \r 100"\x04\x01 58910-Q5510',
                          'logging': False,
                          'obdMultiplexing': True,
                          'request': [b'"\xf1\x00'],
                          'responseAddress': 2009,
                          'subAddress': 0},
                         {'address': 1988,
                          'brand': 'hyundai',
                          'bus': 1,
                          'ecu': 'fwdCamera',
                          'fwVersion': b'\xf1\x00SP2 MFC  AT AUS RHD 1.00 1.02 99210-Q5500 220624',
                          'logging': False,
                          'obdMultiplexing': True,
                          'request': [b'"\xf1\x00'],
                          'responseAddress': 1996,
                          'subAddress': 0},
                         {'address': 2016,
                          'brand': 'hyundai',
                          'bus': 1,
                          'ecu': 'engine',
                          'fwVersion': b'\xf1\x81616G2051\x00\x00\x00\x00\x00\x00\x00\x00',
                          'logging': False,
                          'obdMultiplexing': True,
                          'request': [b'"\xf1\x87\xf1\x81\xf1\x00'],
                          'responseAddress': 2024,
                          'subAddress': 0},
                         {'address': 2004,
                          'brand': 'hyundai',
                          'bus': 1,
                          'ecu': 'eps',
                          'fwVersion': b'\xf1\x87           \xf1\x00SP2 MDPS C 1.00 1.01 56300Q5920          ',
                          'logging': False,
                          'obdMultiplexing': True,
                          'request': [b'"\xf1\x87\xf1\x81\xf1\x00'],
                          'responseAddress': 2012,
                          'subAddress': 0},
                         {'address': 2001,
                          'brand': 'hyundai',
                          'bus': 1,
                          'ecu': 'abs',
                          'fwVersion': b'\xf1\x8758910-Q5510\xf1\x00SP ESC \r 100"\x04\x01 58910-Q5510',
                          'logging': False,
                          'obdMultiplexing': True,
                          'request': [b'"\xf1\x87\xf1\x81\xf1\x00'],
                          'responseAddress': 2009,
                          'subAddress': 0},
                         {'address': 2017,
                          'brand': 'hyundai',
                          'bus': 1,
                          'ecu': 'transmission',
                          'fwVersion': b'\xf1\x87CXNUG49078092JH2\x89\x97iv\xa9UuW\xaaevW\x99\x98\x89\x88Vx\x9f\xffx\xff\xff\xff\x0b\n\xf1\x816V2D40'
                                       b'51\x00\x00\xf1\x006V2B0_C2\x00\x006V2D4051\x00\x00CSP2N20KL1\xf1\xf7\xe2\x10',
                          'logging': False,
                          'obdMultiplexing': True,
                          'request': [b'"\xf1\x87\xf1\x81\xf1\x00'],
                          'responseAddress': 2025,
                          'subAddress': 0},
                         {'address': 1988,
                          'brand': 'hyundai',
                          'bus': 0,
                          'ecu': 'fwdCamera',
                          'fwVersion': b'\xf1\x00SP2 MFC  AT AUS RHD 1.00 1.02 99210-Q5500 220624',
                          'logging': False,
                          'obdMultiplexing': True,
                          'request': [b'"\xf1\x00'],
                          'responseAddress': 1996,
                          'subAddress': 0},
                         {'address': 2016,
                          'brand': 'subaru',
                          'bus': 1,
                          'ecu': 'engine',
                          'fwVersion': b'SPD5P2AS6G2A\x00\x00\x00\x00',
                          'logging': False,
                          'obdMultiplexing': True,
                          'request': [b'>\x00', b'"\xf1\x82'],
                          'responseAddress': 2024,
                          'subAddress': 0},
                         {'address': 2017,
                          'brand': 'subaru',
                          'bus': 1,
                          'ecu': 'transmission',
                          'fwVersion': b'CSP2N20KL1',
                          'logging': False,
                          'obdMultiplexing': True,
                          'request': [b'>\x00', b'"\xf1\x82'],
                          'responseAddress': 2025,
                          'subAddress': 0},
                         {'address': 2017,
                          'brand': 'subaru',
                          'bus': 1,
                          'ecu': 'transmission',
                          'fwVersion': b'CSP2N20KL1',
                          'logging': False,
                          'obdMultiplexing': True,
                          'request': [b'"\xf1\x82'],
                          'responseAddress': 2025,
                          'subAddress': 0},
                         {'address': 2016,
                          'brand': 'subaru',
                          'bus': 1,
                          'ecu': 'engine',
                          'fwVersion': b'SPD5P2AS6G2A\x00\x00\x00\x00',
                          'logging': False,
                          'obdMultiplexing': True,
                          'request': [b'"\xf1\x82'],
                          'responseAddress': 2024,
                          'subAddress': 0},
                         {'address': 2016,
                          'brand': 'volkswagen',
                          'bus': 1,
                          'ecu': 'engine',
                          'fwVersion': b'\xf1\x82SPD5P2AS6G2A\x00\x00\x00\x00',
                          'logging': False,
                          'obdMultiplexing': True,
                          'request': [b'"\xf1\x87\xf1\x89\xf1\x82'],
                          'responseAddress': 2024,
                          'subAddress': 0},
                         {'address': 2017,
                          'brand': 'volkswagen',
                          'bus': 1,
                          'ecu': 'transmission',
                          'fwVersion': b'\xf1\x87CXNUG49078092JH2\x89\x97iv\xa9UuW\xaaevW\x99\x98\x89\x88Vx\x9f\xffx\xff\xff\xff\x0b\n\xf1\x896V2D40'
                                       b'51\x00\x00\xf1\x82CSP2N20KL1',
                          'logging': False,
                          'obdMultiplexing': True,
                          'request': [b'"\xf1\x87\xf1\x89\xf1\x82'],
                          'responseAddress': 2025,
                          'subAddress': 0}],```

**Comment by sunnyhaibin** [comment]
> @sunnyhaibin - hello hello 👋🏼, any objection if we expand this PR to support a 2023 Kia Seltos non-scc as well?
> 
> Harness is the same as above: Hyundai L Hardware is a C3
> 
> Issues / bug so far:
> 
> * Forward collision avoidance gets switched off / disabled (just confirming). Lamp indication is `ON` on instrument cluster as well.
> * Assuming this will be fixed with the added finger printing, but upon first install and connection to the car, it does take a few restarts of C3 and car to successfully detect. If I recall, the error was the classic "CAN connection failure, check cables"
> * Steering control seems to drop off at random when stopped and only becomes active again after a +-25km/h OR changing lanes / inputting manual steering. I haven't been able to pinpoint the exact cause but can definitely say it stops getting applied. Will see if I can locate a route with this.
> * Once in a blue moon, the car will freak out and display the "take break" on the instrument cluster, while C3 errors and has the "take control immediately". No route saved, will make note of this next time.
> * In order to activate MADS, I have to press the LKAS button first, and then Cruise Main.
> * "Camera Frame Rate Low" alert is shown every time when car starts.
> * Shifting gear into S / manual mode causes C3 to freak out.
> 
> Let me know if you need any more info <3
> 
> Full FW dump:
> 
> ```
> 'carFw': [{'address': 2004,
>                           'brand': 'hyundai',
>                           'bus': 1,
>                           'ecu': 'eps',
>                           'fwVersion': b'\xf1\x00SP2 MDPS C 1.00 1.01 56300Q5920          ',
>                           'logging': False,
>                           'obdMultiplexing': True,
>                           'request': [b'"\xf1\x00'],
>                           'responseAddress': 2012,
>                           'subAddress': 0},
>                          {'address': 2017,
>                           'brand': 'hyundai',
>                           'bus': 1,
>                           'ecu': 'transmission',
>                           'fwVersion': b'\xf1\x006V2B0_C2\x00\x006V2D4051\x00\x00CSP2N20KL1\xf1\xf7\xe2\x10',
>                           'logging': False,
>                           'obdMultiplexing': True,
>                           'request': [b'"\xf1\x00'],
>                           'responseAddress': 2025,
>                           'subAddress': 0},
>                          {'address': 2001,
>                           'brand': 'hyundai',
>                           'bus': 1,
>                           'ecu': 'abs',
>                           'fwVersion': b'\xf1\x00SP ESC \r 100"\x04\x01 58910-Q5510',
>                           'logging': False,
>                           'obdMultiplexing': True,
>                           'request': [b'"\xf1\x00'],
>                           'responseAddress': 2009,
>                           'subAddress': 0},
>                          {'address': 1988,
>                           'brand': 'hyundai',
>                           'bus': 1,
>                           'ecu': 'fwdCamera',
>                           'fwVersion': b'\xf1\x00SP2 MFC  AT AUS RHD 1.00 1.02 99210-Q5500 220624',
>                           'logging': False,
>                           'obdMultiplexing': True,
>                           'request': [b'"\xf1\x00'],
>                           'responseAddress': 1996,
>                           'subAddress': 0},
>                          {'address': 2016,
>                           'brand': 'hyundai',
>                           'bus': 1,
>                           'ecu': 'engine',
>                           'fwVersion': b'\xf1\x81616G2051\x00\x00\x00\x00\x00\x00\x00\x00',
>                           'logging': False,
>                           'obdMultiplexing': True,
>                           'request': [b'"\xf1\x87\xf1\x81\xf1\x00'],
>                           'responseAddress': 2024,
>                           'subAddress': 0},
>                          {'address': 2004,
>                           'brand': 'hyundai',
>                           'bus': 1,
>                           'ecu': 'eps',
>                           'fwVersion': b'\xf1\x87           \xf1\x00SP2 MDPS C 1.00 1.01 56300Q5920          ',
>                           'logging': False,
>                           'obdMultiplexing': True,
>                           'request': [b'"\xf1\x87\xf1\x81\xf1\x00'],
>                           'responseAddress': 2012,
>                           'subAddress': 0},
>                          {'address': 2001,
>                           'brand': 'hyundai',
>                           'bus': 1,
>                           'ecu': 'abs',
>                           'fwVersion': b'\xf1\x8758910-Q5510\xf1\x00SP ESC \r 100"\x04\x01 58910-Q5510',
>                           'logging': False,
>                           'obdMultiplexing': True,
>                           'request': [b'"\xf1\x87\xf1\x81\xf1\x00'],
>                           'responseAddress': 2009,
>                           'subAddress': 0},
>                          {'address': 2017,
>                           'brand': 'hyundai',
>                           'bus': 1,
>                           'ecu': 'transmission',
>                           'fwVersion': b'\xf1\x87CXNUG49078092JH2\x89\x97iv\xa9UuW\xaaevW\x99\x98\x89\x88Vx\x9f\xffx\xff\xff\xff\x0b\n\xf1\x816V2D40'
>                                        b'51\x00\x00\xf1\x006V2B0_C2\x00\x006V2D4051\x00\x00CSP2N20KL1\xf1\xf7\xe2\x10',
>                           'logging': False,
>                           'obdMultiplexing': True,
>                           'request': [b'"\xf1\x87\xf1\x81\xf1\x00'],
>                           'responseAddress': 2025,
>                           'subAddress': 0},
>                          {'address': 1988,
>                           'brand': 'hyundai',
>                           'bus': 0,
>                           'ecu': 'fwdCamera',
>                           'fwVersion': b'\xf1\x00SP2 MFC  AT AUS RHD 1.00 1.02 99210-Q5500 220624',
>                           'logging': False,
>                           'obdMultiplexing': True,
>                           'request': [b'"\xf1\x00'],
>                           'responseAddress': 1996,
>                           'subAddress': 0},
>                          {'address': 2016,
>                           'brand': 'subaru',
>                           'bus': 1,
>                           'ecu': 'engine',
>                           'fwVersion': b'SPD5P2AS6G2A\x00\x00\x00\x00',
>                           'logging': False,
>                           'obdMultiplexing': True,
>                           'request': [b'>\x00', b'"\xf1\x82'],
>                           'responseAddress': 2024,
>                           'subAddress': 0},
>                          {'address': 2017,
>                           'brand': 'subaru',
>                           'bus': 1,
>                           'ecu': 'transmission',
>                           'fwVersion': b'CSP2N20KL1',
>                           'logging': False,
>                           'obdMultiplexing': True,
>                           'request': [b'>\x00', b'"\xf1\x82'],
>                           'responseAddress': 2025,
>                           'subAddress': 0},
>                          {'address': 2017,
>                           'brand': 'subaru',
>                           'bus': 1,
>                           'ecu': 'transmission',
>                           'fwVersion': b'CSP2N20KL1',
>                           'logging': False,
>                           'obdMultiplexing': True,
>                           'request': [b'"\xf1\x82'],
>                           'responseAddress': 2025,
>                           'subAddress': 0},
>                          {'address': 2016,
>                           'brand': 'subaru',
>                           'bus': 1,
>                           'ecu': 'engine',
>                           'fwVersion': b'SPD5P2AS6G2A\x00\x00\x00\x00',
>                           'logging': False,
>                           'obdMultiplexing': True,
>                           'request': [b'"\xf1\x82'],
>                           'responseAddress': 2024,
>                           'subAddress': 0},
>                          {'address': 2016,
>                           'brand': 'volkswagen',
>                           'bus': 1,
>                           'ecu': 'engine',
>                           'fwVersion': b'\xf1\x82SPD5P2AS6G2A\x00\x00\x00\x00',
>                           'logging': False,
>                           'obdMultiplexing': True,
>                           'request': [b'"\xf1\x87\xf1\x89\xf1\x82'],
>                           'responseAddress': 2024,
>                           'subAddress': 0},
>                          {'address': 2017,
>                           'brand': 'volkswagen',
>                           'bus': 1,
>                           'ecu': 'transmission',
>                           'fwVersion': b'\xf1\x87CXNUG49078092JH2\x89\x97iv\xa9UuW\xaaevW\x99\x98\x89\x88Vx\x9f\xffx\xff\xff\xff\x0b\n\xf1\x896V2D40'
>                                        b'51\x00\x00\xf1\x82CSP2N20KL1',
>                           'logging': False,
>                           'obdMultiplexing': True,
>                           'request': [b'"\xf1\x87\xf1\x89\xf1\x82'],
>                           'responseAddress': 2025,
>                           'subAddress': 0}],```
> ```

So seems like your car is also CAN platform then! Neat. I'll update the PR with your model year.

> Forward collision avoidance gets switched off / disabled (just confirming). Lamp indication is ON on instrument cluster as well.
That's a weird one. We supposedly don't touch anything with FCW with these cars. Got a route of this?

> Steering control seems to drop off at random when stopped and only becomes active again after a +-25km/h OR changing lanes / inputting manual steering. I haven't been able to pinpoint the exact cause but can definitely say it stops getting applied. Will see if I can locate a route with this.
Sounds like there's a low-speed lockout that's not well-understood yet. Got a route?

> Once in a blue moon, the car will freak out and display the "take break" on the instrument cluster, while C3 errors and has the "take control immediately". No route saved, will make note of this next time.
This seems to be something similar to some CAN-FD platforms cutting out due to attention monitoring from the stock system. This needs further investigation with upstream.

> In order to activate MADS, I have to press the LKAS button first, and then Cruise Main.
Does pressing the CRUISE MAIN button engage SCC immediately on this platform?

> Shifting gear into S / manual mode causes C3 to freak out.
Got a route of this? Might need to have the non-Drive gear handled.

> Assuming this will be fixed with the added finger printing, but upon first install and connection to the car, it does take a few restarts of C3 and car to successfully detect. If I recall, the error was the classic "CAN connection failure, check cables"
> "Camera Frame Rate Low" alert is shown every time when car starts.
I would keep an eye on these errors, and reach out to comma support if it gets worse.

**Pull request merged**
