### PR TITLE
Add Kia K8 Hybrid 2023 carFw

### PR DESCRIPTION
**Pull request by Kirito3481**
**Checklist**
- [x] added entry to CarInfo in selfdrive/car/*/values.py and ran `selfdrive/car/docs.py` to generate new docs
- [ ] test route added to [routes.py](https://github.com/commaai/openpilot/blob/master/selfdrive/car/tests/routes.py)
- [ ] route with openpilot:
- [ ] route with stock system:

### CODE REVIEW

**Comment by sunnyhaibin** [comment]
Thanks for the PR.
- Does this car have factory Smart Cruise Control?
- Any reason why this is not opened with [`commaai/openpilot`](https://github.com/commaai/openpilot)?

**Comment by Kirito3481** [comment]
- Yes, this car has HDA2.
- Tried to use sunnypilot.

**Comment by sunnyhaibin** [comment]
Can you please reach out to me on Discord? We should get this car supported in stock openpilot. Once it is supported in stock openpilot, it will be supported in sunnypilot.
- https://discord.sunnypilot.com

**Comment by sunnyhaibin** [comment]
This car requires a car port in [`commaai/openpilot`](https://github.com/commaai/openpilot). Closing as this PR has been superseded by the car port effort in upstream.
- https://github.com/commaai/openpilot/pull/29899

**Pull request closed without merging**
