### PR TITLE
Honda: Car Port for Accord 4-Cylinder 9th Generation

### PR DESCRIPTION
**Pull request by mlocoteta**
Had to clean up some stuff in DBC.

9th Generation model-years have ALC data over serial lines and require third-party hardware to interface with openpilot. For more information, see [mlocoteta's GitHub](https://github.com/mlocoteta/serialSteeringHardware).

**Requires**
- Serial Steering Hardware from [mlocoteta's GitHub](https://github.com/mlocoteta/serialSteeringHardware)
- https://github.com/sunnyhaibin/opendbc/pull/4

### CODE REVIEW

**Comment by sunnyhaibin** [comment]
Thanks for the PR. Wanna make a PR with the DBC changes against [sunnypilot's openDBC's `master`](https://github.com/sunnyhaibin/opendbc) branch?

**Comment by sunnyhaibin** [comment]
Can you please merge with the latest?

**Comment by mlocoteta** [comment]
Need to test after pushing update

**Comment by mlocoteta** [comment]
Works as expected. Submitted PR for opendbc as well.

**Comment by sunnyhaibin** [comment]
- Requires https://github.com/sunnyhaibin/opendbc/pull/4

**Comment by sunnyhaibin** [comment]
@mlocoteta has confirmed that everything is working as expected after the cleanup changes.

Thanks for the PR! 🎉

**Pull request merged**
